apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-simple-app-ingress
  namespace: dev
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: simple-app-service
            port:
              number: 80
  ingressClassName: nginx
